### ISSUE TITLE
Don't have weight file

### ISSUE THREAD

**Issue by chienbienbac** [cannguyen275/1MB-License-Plate-Detection-With-4-Landmarks#1]
Hi Kei,
Please share your weight file.
'weights/CCPD/CCPD_150.pth'
Thanks!

**Comment by cannguyen275** [comment]
Hi @chienbienbac 
Pls pull the latest commit:
https://github.com/cannguyen275/1MB-License-Plate-Detection-With-4-Landmarks/tree/main/weights/CCPD

Thanks,
Kei
